### ISSUE TITLE
Scharrel, barrel, etc

### ISSUE THREAD

**Issue by Lukas97** [patbro/sinus-app#7]
https://man-man.nl/scharrel-twarrel-kwarrel-relaties/

**Comment by LoeHendriks** [comment]
[](url)
<img width="368" alt="Screenshot 2022-09-25 at 19 31 23" src="https://user-images.githubusercontent.com/33540511/192157104-50f1303e-32d2-4bbd-9479-8340f43d7ed3.png">
Done!
